db:
  image: mysql:5.7
  ports:
    - '3306'
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  volumes:
    - ./Autolab/docker/mysql:/etc/mysql/conf.d
    - ./db-data:/var/lib/mysql

tango:
#  build: ./Tango
  image: local_tango_connor
#  command: sh start.sh
  ports:
    - '8600:8600'
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  - /opt/TangoService/Tango/volumes:/opt/TangoService/Tango/volumes
#  privileged: true


web:
  build: ./Autolab
  links:
    - db
    - tango
  ports:
    - '80:80'
    - '443:443'
  volumes:
    - ./Autolab/courses:/home/app/webapp/courses
